"""trips become user-created expense-bounded groupings

Revision ID: 3be6ae992ffe
Revises: 9e523da357a9
Create Date: 2026-08-08 10:27:34.124062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '3be6ae992ffe'
down_revision = '9e523da357a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Existing rows were machine-inferred groupings of visits. The new model is
    # a user-made grouping bounded by two expenses — there is nothing to convert,
    # so they are dropped. Visits, photos and expenses are untouched.
    op.execute('DELETE FROM trips')

    op.add_column('trips', sa.Column('start_expense_id', sa.Integer(), nullable=False))
    op.add_column('trips', sa.Column('end_expense_id', sa.Integer(), nullable=False))
    op.add_column('trips', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('trips', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('trips', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_trips_started_at'), table_name='trips')
    op.create_foreign_key(
        'fk_trips_start_expense', 'trips', 'expenses', ['start_expense_id'], ['id'],
        ondelete='RESTRICT',
    )
    op.create_foreign_key(
        'fk_trips_end_expense', 'trips', 'expenses', ['end_expense_id'], ['id'],
        ondelete='RESTRICT',
    )
    op.drop_column('trips', 'ended_at')
    op.drop_column('trips', 'started_at')
    op.drop_column('trips', 'pinned')
    op.drop_column('trips', 'kind')
    op.drop_column('trips', 'auto_title')
    op.drop_index(op.f('ix_visits_trip_id'), table_name='visits')
    op.drop_constraint(op.f('visits_trip_id_fkey'), 'visits', type_='foreignkey')
    op.drop_column('visits', 'trip_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('visits_trip_id_fkey'), 'visits', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_visits_trip_id'), 'visits', ['trip_id'], unique=False)
    op.add_column('trips', sa.Column('auto_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('trips', sa.Column('kind', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('trips', sa.Column('pinned', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('trips', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('trips', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('fk_trips_end_expense', 'trips', type_='foreignkey')
    op.drop_constraint('fk_trips_start_expense', 'trips', type_='foreignkey')
    op.create_index(op.f('ix_trips_started_at'), 'trips', ['started_at'], unique=False)
    op.alter_column('trips', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('trips', 'created_at')
    op.drop_column('trips', 'note')
    op.drop_column('trips', 'end_expense_id')
    op.drop_column('trips', 'start_expense_id')
    # ### end Alembic commands ###
