"""trip recommendations

Revision ID: 558b18139eee
Revises: b41c7d2a58e9
Create Date: 2026-08-08 13:01:42.160784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '558b18139eee'
down_revision = 'b41c7d2a58e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anchor_visit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tz_offset_minutes', sa.Integer(), nullable=False),
    sa.Column('moment', sa.String(length=120), nullable=True),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_recommendations_trip_id'), 'trip_recommendations', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_recommendations_user_id'), 'trip_recommendations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_recommendations_user_id'), table_name='trip_recommendations')
    op.drop_index(op.f('ix_trip_recommendations_trip_id'), table_name='trip_recommendations')
    op.drop_table('trip_recommendations')
    # ### end Alembic commands ###
