"""split expense what and where

Revision ID: 9e523da357a9
Revises: fde5af11f61c
Create Date: 2026-08-08 09:34:55.503972

"""
from alembic import op
import sqlalchemy as sa


revision = '9e523da357a9'
down_revision = 'fde5af11f61c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('place_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_expenses_place_id', 'expenses', 'places', ['place_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_expenses_place_id', 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'place_id')
    op.drop_column('expenses', 'description')
    # ### end Alembic commands ###
