"""multi-currency and manual expenses

Revision ID: fde5af11f61c
Revises: 27d02d5ca8af
Create Date: 2026-08-08 09:01:31.116624

"""
from alembic import op
import sqlalchemy as sa


revision = 'fde5af11f61c'
down_revision = '27d02d5ca8af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'as_of_date', name='uq_exchange_rates_pair_date')
    )
    # server_default backfills existing rows; dropped afterwards so the app
    # (not the database) stays in charge of the values it writes.
    op.add_column(
        'expenses',
        sa.Column('source', sa.String(length=16), nullable=False, server_default='receipt'),
    )
    op.add_column(
        'expenses',
        sa.Column('base_currency', sa.String(length=3), nullable=False, server_default='THB'),
    )
    op.add_column('expenses', sa.Column('base_total_minor', sa.BigInteger(), nullable=True))
    op.add_column('expenses', sa.Column('fx_rate', sa.Numeric(precision=20, scale=10), nullable=True))
    op.add_column('expenses', sa.Column('fx_rate_source', sa.String(length=16), nullable=True))
    op.add_column(
        'expenses',
        sa.Column('needs_review', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # Pre-existing rows were single-currency: they are already their own base.
    op.execute(
        """
        UPDATE expenses
           SET base_currency = currency,
               base_total_minor = total_minor,
               fx_rate = 1,
               fx_rate_source = 'same'
        """
    )
    for column in ('source', 'base_currency', 'needs_review'):
        op.alter_column('expenses', column, server_default=None)
    op.alter_column('expenses', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_expenses_needs_review'), 'expenses', ['needs_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_needs_review'), table_name='expenses')
    op.alter_column('expenses', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('expenses', 'needs_review')
    op.drop_column('expenses', 'fx_rate_source')
    op.drop_column('expenses', 'fx_rate')
    op.drop_column('expenses', 'base_total_minor')
    op.drop_column('expenses', 'base_currency')
    op.drop_column('expenses', 'source')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
